stages:
- stage: 'BlackDuck_Scan'
  jobs:
    - job: detect
      steps:
      - task: CmdLine@2
        displayName: 'Install npm dependencies'
        inputs:
          script: |
            find . -name "package.json" -type f -print0 |
            xargs -0 -I {} sh -c '
              dir=$(dirname "{}")
              cd "$dir" && npm install --lockfile-version 3 --package-lock-only --force || echo "Failed to generate package-lock.json in $dir"
            '
      
      - task: CmdLine@2
        displayName: 'Install Python dependencies'
        inputs:
          script: |
            find . -name "requirements.txt" -type f -exec sh -c '
              for req in "$@"; do
                  while IFS= read -r package || [ -n "$package" ]; do
                      pip install --no-cache-dir --no-clean --no-deps "$package" || echo "Failed to install $package"
                  done < "$req"
              done
            ' sh {} +

      - task: SynopsysDetectTask@9
        displayName: 'Run Synopsys Detect'
        inputs:
          BlackDuckService: 'BlackDuck'
          DetectArguments: |
            --detect.project.name=Node-Py-test
            --detect.project.version.name=Ongoing_Build_Yaml 
            --blackduck.trust.cert=true  
            --detect.detector.search.depth=100  
            --detect.tools=DETECTOR  
            --detect.detector.search.continue=true
          DetectVersion: 'latest'

